### ISSUE TITLE
Notifications Issue

### ISSUE THREAD

**Issue by NablaMetal** [Andrewerr/NextcloudServices#42]
Hey, thanks a lot for fixing #39 
Unfortunately, nextcloud notifications (any) aren't working at all on my device with the 1.0-beta13 latest release.
I go back with the working beta12 for now.

device : pixel7, grapheneOS latest build
nextcloud server : docker 25.0.3 latest

If I can help, please provide the information you may need, if I can.
have a nice day

**Comment by Andrewerr** [comment]
Hello. Thank you for reporting this issue. It may be since Android 13 requires a permission to show notifications and does not recognise my app as containing legacy code. I would try to fix it by checking this emulator. 
 Unfortunately GrapheneOS does not publish emulator images(and my own ROM has not moved to A13 codebase), so I would blindly use a Google's emulator which definetely have significantly different codebase

**Comment by NablaMetal** [comment]
OK, anyway I confirm I cannot enable notifications in the android application settings (the place where one can manage security, permissions etc. for each app ) for nextcloud services 1.0beta13, like it wouldn't notice this app requires access to notifications.

**Comment by freeflyk** [comment]
Hello Andrewerr.

I tested the implementation on LOS 20.0 (Android 13) and it seems there is still the wrong permission set. I created a pull request that uses the POST_NOTIFICATION permission instead and this code runs fine with my device + emulator.

**Comment by Andrewerr** [comment]
Hello freeflyk 
Thank you for fixing and testing it
