### ISSUE TITLE
Monochrome icon

### ISSUE THREAD

**Issue by julianfairfax** [Andrewerr/NextcloudServices#63]
A monochrome icon would be a nice addition to make Nextcloud Services blend in on the Android home screen.

**Comment by Andrewerr** [comment]
Thankyou for suggestion. Unfortunately I am not sure whether it is possible, since what I have seen in custom ROMs(like crDroid and LineageOS) the monochrome icons are either generated automatically or just pre-installed to the ROM. Though I will look into whether the AOSP default API has any specific support for icon theming from app itself

**Comment by julianfairfax** [comment]
Any app can add a monochrome icon. It is as simple as this: https://github.com/aivanovski/kpassnotes/pull/134/commits/664c8c182cf1ff542151e882dd0bf3b0de87f0a2 (although you may have to modify the foreground file a bit, to make it look nice).

**Comment by Andrewerr** [comment]
Thankyou for giving an example. I would add a monochrome icon in one of next releases
